### ISSUE TITLE
Profile.vue

### ISSUE THREAD

**Issue by deokgoo** [DohwanKim/vue-myline-master#10]

**Comment by deokgoo** [comment]
22번째줄 img src => v-bind사용하기

**Comment by DohwanKim** [comment]
user: {username: name...., userImage: src....} 형태를 가져와서 v-bind를 사용하여 이미지 출력.
+ Profile.vue -> ProfileView.vue 로 파일 이름 변경.

**Comment by DohwanKim** [comment]
* 수정 후 푸시 *
