### ISSUE TITLE
MainView.vue

### ISSUE THREAD

**Issue by deokgoo** [DohwanKim/vue-myline-master#11]

**Comment by deokgoo** [comment]
1. v-for활용 할 수 있으면 활용하기
2. img src -> v-bind 변경

**Comment by DohwanKim** [comment]
좌측 사이드 부분을 상단과 하단을 나눠 v-for로 사용.
친구리스트를 v-for를 사용하고 내부 이미지를 v-bind를 사용하여 출력

**Comment by DohwanKim** [comment]
*수정 후 푸시*
