### ISSUE TITLE
LoginView.vue

### ISSUE THREAD

**Issue by deokgoo** [DohwanKim/vue-myline-master#12]

**Comment by deokgoo** [comment]
auth.id => auth.idText
auth.pw => auth.pwText
변수명 생각해보기

**Comment by DohwanKim** [comment]
id, pw 자체로만 지칭하면 포괄적인 지칭이 됨으로 변수의 데이터 형태를 파악하기 어려움.
혹은 다른 id, pw 데이터와 혼동 가능성 존재.
text라 추가로 지칭해주고 input에서 오는 텍스트라 해주는게 좋다는 의미로 해석.

**Comment by deokgoo** [comment]
> id, pw 자체로만 지칭하면 포괄적인 지칭이 됨으로 변수의 데이터 형태를 파악하기 어려움.
> 혹은 다른 id, pw 데이터와 혼동 가능성 존재.
> text라 추가로 지칭해주고 input에서 오는 텍스트라 해주는게 좋다는 의미로 해석.

정답~

**Comment by DohwanKim** [comment]
*수정 후 푸시*
