### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by deokgoo** [DohwanKim/vue-myline-master#5]
bug

**Comment by DohwanKim** [comment]
wtf?

**Comment by deokgoo** [comment]
#e83af6d7f0575485fdad54c7279ded420458b42e

**Comment by deokgoo** [comment]
e83af6d

**Comment by deokgoo** [comment]
2b5829a

**Comment by deokgoo** [comment]
350033

**Comment by deokgoo** [comment]
[2b5829a](https://github.com/DohwanKim/vue-myline-master/commit/2b5829ab9418668fa185c17be0d3a730ae079505#r35003336)

**Comment by deokgoo** [comment]
[hoge.vue](https://github.com/DohwanKim/vue-myline-master/commit/2b5829ab9418668fa185c17be0d3a730ae079505#r35003336) 수정바람

**Comment by DohwanKim** [comment]
> [hoge.vue](https://github.com/DohwanKim/vue-myline-master/commit/2b5829ab9418668fa185c17be0d3a730ae079505#r35003336) 수정바람

수정 완료

**Comment by DohwanKim** [comment]
> [2b5829a](https://github.com/DohwanKim/vue-myline-master/commit/2b5829ab9418668fa185c17be0d3a730ae079505#r35003336)

check
