### ISSUE TITLE
Home.vue

### ISSUE THREAD

**Issue by deokgoo** [DohwanKim/vue-myline-master#8]

**Comment by deokgoo** [comment]
아무리 찾아도 2500개를 다 뒤져서 코멘트 다는건 무리라는 것으로 판단
node_modules 올린건 엄청난 실수
[Home.vue](https://github.com/DohwanKim/vue-myline-master/blob/nBranch/src/views/Home.vue)
selectTab => store(vuex) state로 변경
changeTab => store(vuex) action으로 변경

**Comment by DohwanKim** [comment]
https://joshua1988.github.io/web-development/vuejs/vuex-start/#%EB%93%A4%EC%96%B4%EA%B0%80%EB%A9%B0

https://joshua1988.github.io/web-development/vuejs/vuejs-tutorial-for-beginner/

를 통해 로직 이해중

**Comment by deokgoo** [comment]
흠흠.. 이부분 설명 하겠습니다~
